#!/usr/bin/env node
const commandLineArgs = require('command-line-args');
const getUsage = require('command-line-usage');

const menu = require('./src/Model/Menu');
const Args = require('./src/Model/Args');
const CrawlService = require('./src/Service/CrawlService');
const SitemapService = require('./src/Service/SitemapService');

let args = new Args(commandLineArgs(menu[1]['optionList']));

if (args.shouldShowHelp()) {
    console.log(getUsage(menu));
} else {
    args.output.doesFolderExist();
    console.log('\nStarting Site Index');
    if (args.isCrawl()) {
        let crawlService = new CrawlService(args);
        crawlService
            .on('progress', progress => {
                if (args.verbose) {
                    console.log(progress.toString());
                }
            })
            .on('complete', () => console.log('Done'));
        crawlService.start();
    } else if (args.isSingle()) {
        let singleService = new SingleService(args);
        singleService.start();
    } else {
        let sitemapService = new SitemapService(args);
        sitemapService
            .on('progress', progress => {
                if (args.verbose) {
                    console.log(progress.toString());
                }
            })
            .on('complete', () => console.log('Done'));
        sitemapService.start();
    }
}