#!/usr/bin/env node
const commandLineArgs = require('command-line-args');
const getUsage = require('command-line-usage');

const IndexController = require('./src/Controller/IndexController');
const menu = require('./src/Model/Menu');
const Args = require('./src/Model/Args');

let args = new Args(commandLineArgs(menu[1]['optionList']));

if (args.shouldShowHelp()) {
    console.log(getUsage(menu));
} else {
    console.log('\nStarting Site Index');
    let indexController = new IndexController(args);
    indexController.start().then();
}